### ISSUE TITLE
Linux RecvBytes, SendBytes 함수 버그

### ISSUE THREAD

**Issue by yschungmr** [nearthlab/ladgnss#6]
@KyubeomLee 
RecvBytes, SendBytes 함수 buffer 읽고 쓰는 부분에 버그가 있습니다.
Linux read함수와 write 함수의 인자를 확인하세요.
한번 생각해보고 코멘트 달기 바랍니다.

**Comment by KyubeomLee** [comment]
read/ write = int, void*, size_t를 인자로 받습니다.
여기서 두번재 인자를 &로 하여 넣어서 문제가 됩니다. 
수정하였습니다.

**Comment by yschungmr** [comment]
아까 사무실에서 한참 찾아봤던 대로, 내 상식하고 다르게 어떤 컴파일러에서는 &array가 array[0]의 주소값이 됩니다. 즉, 아래 3개는 모두 값이 같습니다.
```C
char array[16];

(void*)&array
(void*)array
(void*)&(array[0])
```
결국 버그는 아니었지만, 스탠다드 코딩이라고 보기는 (컴파일러마다 다르게 동작하므로) 어려울 것 같으므로 앞으로는 신경써서 코딩하기 바랍니다.
덕분에 좋은거 배웠습니다 ㅎㅎ
